version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    #environment:
     # - TZ=America/New_York
    restart: always
    #network_mode: host
    ports:
      - 8123:8123
  broker: # mosquitto
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log/
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 1883:1883 
      - 9001:9001
  banco_dados:
    image:  influxdb
    volumes:
            #- ./influxdb/data:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_USERNAME=my_user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - INFLUXDB_DB=my_database
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket 
    restart: always
    ports: 
      - 8086:8086

