#################################################################
#                                                               #
#                          MIDNIGHT                             #
#                                                               #
#################################################################

midnight:

  background-image: "center / cover no-repeat url('/local/background.jpg') fixed"
  ha-card-background: "rgba(128, 128, 128, 0.1)"
  ha-card-border-radius: "7px"
  ha-card-box-shadow: "3px 3px 13px -6px rgba(0,0,0,1)"
  label-badge-text-color: "#ffffff"
  label-badge-background-color: "#21252b"
  sidebar-background-color: "#000000"
  sidebar-icon-color: "#03a9f4"
  switch-checked-color: "#03a9f4"
  switch-unchecked-color: "#7f848e"
  switch-unchecked-button-color: "#7f848e"
  table-row-background-color: "#2c3139"
  table-row-alternative-background-color: "#424a56"

  # The items below are some of the default values from 
  # https://github.com/home-assistant/frontend/blob/master/src/resources/ha-style.ts 
  # Where the default value isn't changed, its noted.

  #Text
  primary-text-color: "#ffffff"
  secondary-text-color: "#b3b3b3"
  text-primary-color: "#ffffff"
  disabled-text-color: "#7f848e"

  #Main interface colors
  primary-color: "#03a9f4"
  dark-primary-color: "#03a9f4"
  light-primary-color: "#03a9f4"
  accent-color: "#03a9f4"
  divider-color: "rgb(50, 52, 56, 0.5)"
  scrollbar-thumb-color: "rgb(194, 194, 194)" #Default Value
  error-color: "#db4437" #Default Value
  warning-color: "#f4b400" #Default Value
  success-color: "#0f9d58" #Default Value
  info-color: "#4285f4" #Default Value

  #States and badges
  state-icon-color: "#03a9f4"
  state-icon-active-color: "#ffff00"

  #Background and sidebar
  card-background-color: "#000000"
  primary-background-color: "#000000"
  secondary-background-color: "#5e5e5e"

  #For label-badge
  label-badge-red: "#df4c1e" #Default Value
  label-badge-blue: "#039be5" #Default Value
  label-badge-green: "#0da035" #Default Value
  label-badge-yellow: "#f4b400" #Default Value

  #Paper items - These Need to Be removed/repalced based on Breaking Changes in 0.113.0 release notes
  paper-grey-50: "#fafafa" #Default Value
  paper-grey-200: "#eeeeee" #Default Value
  paper-grey-500: "#9e9e9e" #Default Value
  paper-green-400: "#66bb6a" #Default Value
  paper-blue-400: "#42a5f5" #Default Value
  paper-orange-400: "#ffa726" #Default Value

  #Markdown styles
  markdown-code-background-color: "#5e5e5e"

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################